// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package activemqconnector.actions;

import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import org.apache.activemq.ActiveMQConnection;
import org.apache.activemq.ActiveMQConnectionFactory;
import org.apache.activemq.command.ActiveMQQueue;
import javax.jms.Connection;
import activemqconnector.helper.ActiveMQConnectorHelper;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class PurgeQueue extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __configuration;
	private activemqconnector.proxies.AMQConfiguration configuration;
	private java.lang.Boolean forceDelete;

	public PurgeQueue(IContext context, IMendixObject configuration, java.lang.Boolean forceDelete)
	{
		super(context);
		this.__configuration = configuration;
		this.forceDelete = forceDelete;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.configuration = __configuration == null ? null : activemqconnector.proxies.AMQConfiguration.initialize(getContext(), __configuration);

		// BEGIN USER CODE
		if (configuration == null) throw new IllegalArgumentException("Input object is empty");
		
		Connection  connection = null;

		try {
			ActiveMQConnectionFactory factory = ActiveMQConnectorHelper.createConnectionFactory(configuration);
	        connection = factory.createConnection();
//			connection.start();
			String queueName = configuration.getQueueName();
			((ActiveMQConnection) connection).destroyDestination(new ActiveMQQueue(queueName));
		} catch (Exception e) {
			throw new MendixRuntimeException("Failed to delete queue", e);
		} finally {
	        if (connection != null) connection.close();
		}
        return true;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PurgeQueue";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
